grpc:
  host: "postgres"
  port: ":50051"

http:
  host: "postgres"
  port: ":8000"

database:
  host: "postgres"
  port: "5432"
  user: "postgres"
  database: "notes_db"
  ssl: "disable"
  max_opened_connections: 10