version: "3"

volumes:
  app-volume:
  postgres-volume:

services:
  postgres:
    image: postgres:14-alpine3.15
    container_name: 'postgres'
    environment:
      - "POSTGRES_DB=notes_db"
      - "POSTGRES_PASSWORD=notes_pass"
      - "POSTGRES_USER=postgres"
      - "PGDATA=/var/lib/postgresql/data/notification"
    volumes: 
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    image: nikitads9/note-service:app
    container_name: 'app'
    ports:
      - "50051:50051"
      - "8000:8000"
    depends_on:
      - postgres
    links:
      - postgres

